# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_compute_disks resource.'

project_name = attribute(:gcp_project_name, default: '')
zone = attribute(:gcp_zone, default: 'zone')
disk_name = attribute(:gcp_compute_disk_name, default: 'my_disk')
disk_image = attribute(:gcp_compute_disk_image, default: 'debian-8-jessie-v20170523')
disk_type = attribute(:gcp_compute_disk_type, default: 'pd-standard')
control 'google_compute_disks-1.0' do
  impact 1.0
  title 'google_compute_disks resource test'

  most_recent_image = google_compute_image({project: disk_image.split('/').first, name: disk_image.split('/').last})
  describe google_compute_disks({project: project_name, zone: zone}) do
    it { should exist }
    its('names') { should include disk_name }
    its('source_images') { should include most_recent_image.self_link }
  end
end
