# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_compute_disk resource.'

project_name = attribute(:gcp_project_name, default: '')
zone = attribute(:gcp_zone, default: 'zone')
disk_name = attribute(:gcp_compute_disk_name, default: 'my_disk')
disk_image = attribute(:gcp_compute_disk_image, default: 'debian-8-jessie-v20170523')
disk_type = attribute(:gcp_compute_disk_type, default: 'pd-standard')
control 'google_compute_disk-1.0' do
  impact 1.0
  title 'google_compute_disk resource test'

  most_recent_image = google_compute_image({project: disk_image.split('/').first, name: disk_image.split('/').last})

  describe google_compute_disk({project: project_name, name: disk_name, zone: zone}) do
    it { should exist }
    # Test that the image is the most recent image for the family
    its('source_image') { should match most_recent_image.self_link }
    its('type') { should match disk_type }
  end

  describe.one do
   	google_compute_disk({project: project_name, name: disk_name, zone: zone}).labels.each_pair do |key, value|
      describe key do
        it { should cmp "environment" }
      end
    end
  end
end
