# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_dns_managed_zone resource.'

gcp_project_id = attribute(:gcp_project_id, default: 'gcp_project_id', description: 'The GCP project identifier.')
managed_zone = attribute('managed_zone', default: {
  "name": "inspec-gcp-managed-zone",
  "dns_name": "my.domain.com.",
  "description": "A test DNS zone",
  "label_key": "key",
  "label_value": "value"
})
control 'google_dns_managed_zone-1.0' do
  impact 1.0
  title 'google_dns_managed_zone resource test'

  describe google_dns_managed_zone(project: gcp_project_id, name: managed_zone['name']) do
    it { should exist }
    its('name') { should eq managed_zone['name'] }
    its('dns_name') { should eq managed_zone['dns_name'] }
    its('description') { should include managed_zone['description'] }
  end
end
