# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_dns_managed_zones resource.'

gcp_project_id = attribute(:gcp_project_id, default: 'gcp_project_id', description: 'The GCP project identifier.')
managed_zone = attribute('managed_zone', default: {
  "name": "inspec-gcp-managed-zone",
  "dns_name": "my.domain.com.",
  "description": "A test DNS zone",
  "label_key": "key",
  "label_value": "value"
})
control 'google_dns_managed_zones-1.0' do
  impact 1.0
  title 'google_dns_managed_zones resource test'

  describe google_dns_managed_zones(project: gcp_project_id) do
    its('count') { should eq 1 }
    its('names') { should include managed_zone['name'] }
    its('dns_names') { should include managed_zone['dns_name'] }
    its('descriptions') { should include managed_zone['description'] }
  end
end
