# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

title 'Test GCP google_appengine_standard_app_version resource.'

gcp_project_id = attribute(:gcp_project_id, default: 'gcp_project_id', description: 'The GCP project identifier.')
gcp_location = attribute(:gcp_location, default: 'gcp_location', description: 'The GCP project location.')
standardappversion = attribute('standardappversion', default: {
  "name": "apps/gcp-project-name/services/default/versions/v2",
  "id": "v2",
  "service": "default",
  "runtime": "nodejs10",
  "entrypoint": "hello",
  "env_var_value": "val1"
}, description: 'Cloud App Engine definition')
control 'google_appengine_standard_app_version-1.0' do
  impact 1.0
  title 'google_appengine_standard_app_version resource test'


  describe google_appengine_standard_app_version(project: gcp_project_id, location: gcp_location, version_id: standardappversion['version_id'], service: standardappversion['service']) do
    it { should exist }
    its('service') { should eq standardappversion['service'] }
    its('name') { should eq standardappversion['name'] }
    its('id') { should eq standardappversion['version_id'] }
    its('env_variables') { should eq standardappversion['env_var_value'] }
    its('runtime_api_version') { should eq standardappversion['runtime_api_version'] }
    its('runtime') { should eq standardappversion['runtime'] }
    its('entrypoint') { should eq standardappversion['entrypoint'] }
  end
end
