# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
module GoogleInSpec
  module AppEngine
    module Property
      class StandardAppVersionHandlersStaticFiles
        attr_reader :path

        attr_reader :upload_path_regex

        attr_reader :http_headers

        attr_reader :mime_type

        attr_reader :expiration

        attr_reader :require_matching_file

        attr_reader :application_readable

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @path = args['path']
          @upload_path_regex = args['uploadPathRegex']
          @http_headers = args['httpHeaders']
          @mime_type = args['mimeType']
          @expiration = args['expiration']
          @require_matching_file = args['requireMatchingFile']
          @application_readable = args['applicationReadable']
        end

        def to_s
          "#{@parent_identifier} StandardAppVersionHandlersStaticFiles"
        end
      end
    end
  end
end
