# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/appengine/property/standardappversion_deployment_files'
require 'google/appengine/property/standardappversion_deployment_zip'
module GoogleInSpec
  module AppEngine
    module Property
      class StandardAppVersionDeployment
        attr_reader :zip

        attr_reader :files

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @zip = GoogleInSpec::AppEngine::Property::StandardAppVersionDeploymentZip.new(args['zip'], to_s)
          @files = args['files']
        end

        def to_s
          "#{@parent_identifier} StandardAppVersionDeployment"
        end
      end
    end
  end
end
