# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/appengine/property/standardappversion_handlers_script'
require 'google/appengine/property/standardappversion_handlers_static_files'
module GoogleInSpec
  module AppEngine
    module Property
      class StandardAppVersionHandlers
        attr_reader :url_regex

        attr_reader :security_level

        attr_reader :login

        attr_reader :auth_fail_action

        attr_reader :redirect_http_response_code

        attr_reader :script

        attr_reader :static_files

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @url_regex = args['urlRegex']
          @security_level = args['securityLevel']
          @login = args['login']
          @auth_fail_action = args['authFailAction']
          @redirect_http_response_code = args['redirectHttpResponseCode']
          @script = GoogleInSpec::AppEngine::Property::StandardAppVersionHandlersScript.new(args['script'], to_s)
          @static_files = GoogleInSpec::AppEngine::Property::StandardAppVersionHandlersStaticFiles.new(args['staticFiles'], to_s)
        end

        def to_s
          "#{@parent_identifier} StandardAppVersionHandlers"
        end
      end

      class StandardAppVersionHandlersArray
        def self.parse(value, parent_identifier)
          return if value.nil?
          return StandardAppVersionHandlers.new(value, parent_identifier) unless value.is_a?(::Array)
          value.map { |v| StandardAppVersionHandlers.new(v, parent_identifier) }
        end
      end
    end
  end
end
