# Copyright 2018 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

require 'google/compute/property/subnetwork_secondary_ip_ranges'
require 'inspec/resource'

# A provider to manage Google Compute Engine resources.
class Subnetwork < Inspec.resource(1)

  name 'google_compute_subnetwork'
  desc 'Subnetwork'
  supports platform: 'gcp2'

  attr_reader :creation_timestamp
  attr_reader :description
  attr_reader :gateway_address
  attr_reader :id
  attr_reader :ip_cidr_range
  attr_reader :name
  attr_reader :network
  attr_reader :enable_flow_logs
  attr_reader :fingerprint
  attr_reader :secondary_ip_ranges
  attr_reader :private_ip_google_access
  attr_reader :region
  def base
    'https://www.googleapis.com/compute/v1/'
  end

  def url
    'projects/{{project}}/regions/{{region}}/subnetworks/{{name}}'
  end

  def initialize(params)
    @fetched = fetch_resource(params)
    parse unless @fetched.nil?
  end

  def fetch_resource(params)
    get_request = inspec.backend.fetch(base, url, params)
  end

  def initialize(params)
    @fetched = fetch_resource(params)
    parse unless @fetched.nil?
  end

  def fetch_resource(params)
    get_request = inspec.backend.fetch(base, url, params)
  end

  def parse
    @creation_timestamp = DateTime.parse(@fetched['creationTimestamp'])
    @description = @fetched['description']
    @gateway_address = @fetched['gatewayAddress']
    @id = @fetched['id']
    @ip_cidr_range = @fetched['ipCidrRange']
    @name = @fetched['name']
    @network = @fetched['network']
    @enable_flow_logs = @fetched['enableFlowLogs']
    @fingerprint = @fetched['fingerprint']
    @secondary_ip_ranges = Google::Compute::Property::SubnetworkSecondaryiprangesArray.parse(@fetched['secondaryIpRanges'])
    @private_ip_google_access = @fetched['privateIpGoogleAccess']
    @region = @fetched['region']
  end

  def exists?
    !@fetched.nil?
  end
end
