# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'gcp_backend'

# A provider to manage Google Cloud DNS resources.
class ManagedZone < GcpResourceBase
  name 'google_dns_managed_zone'
  desc 'ManagedZone'
  supports platform: 'gcp'

  attr_reader :description
  attr_reader :dns_name
  attr_reader :id
  attr_reader :name
  attr_reader :name_servers
  attr_reader :name_server_set
  attr_reader :creation_time
  attr_reader :labels
  def base
    'https://www.googleapis.com/dns/v1/'
  end

  def url
    'projects/{{project}}/managedZones/{{name}}'
  end

  def initialize(params)
    super(params.merge({ use_http_transport: true }))
    @fetched = @connection.fetch(base, url, params)
    parse unless @fetched.nil?
  end

  def parse
    @description = @fetched['description']
    @dns_name = @fetched['dnsName']
    @id = @fetched['id']
    @name = @fetched['name']
    @name_servers = @fetched['nameServers']
    @name_server_set = @fetched['nameServerSet']
    @creation_time = parse_time_string(@fetched['creationTime'])
    @labels = @fetched['labels']
  end

  # Handles parsing RFC3339 time string
  def parse_time_string(time_string)
    time_string ? Time.parse(time_string) : nil
  end

  def exists?
    !@fetched.nil?
  end
end
