# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'gcp_backend'
require 'google/appengine/property/standardappversion_deployment'
require 'google/appengine/property/standardappversion_deployment_files'
require 'google/appengine/property/standardappversion_deployment_zip'
require 'google/appengine/property/standardappversion_entrypoint'
require 'google/appengine/property/standardappversion_handlers'
require 'google/appengine/property/standardappversion_libraries'

# A provider to manage App Engine resources.
class StandardAppVersion < GcpResourceBase
  name 'google_appengine_standard_app_version'
  desc 'StandardAppVersion'
  supports platform: 'gcp'

  attr_reader :params
  attr_reader :name
  attr_reader :version_id
  attr_reader :runtime
  attr_reader :threadsafe
  attr_reader :runtime_api_version
  attr_reader :handlers
  attr_reader :libraries
  attr_reader :env_variables
  attr_reader :deployment
  attr_reader :entrypoint
  attr_reader :service

  def initialize(params)
    super(params.merge({ use_http_transport: true }))
    @params = params
    @fetched = @connection.fetch(product_url, resource_base_url, params)
    parse unless @fetched.nil?
  end

  def parse
    @name = @fetched['name']
    @version_id = @fetched['id']
    @runtime = @fetched['runtime']
    @threadsafe = @fetched['threadsafe']
    @runtime_api_version = @fetched['runtimeApiVersion']
    @handlers = GoogleInSpec::AppEngine::Property::StandardAppVersionHandlersArray.parse(@fetched['handlers'], to_s)
    @libraries = GoogleInSpec::AppEngine::Property::StandardAppVersionLibrariesArray.parse(@fetched['libraries'], to_s)
    @env_variables = @fetched['envVariables']
    @deployment = GoogleInSpec::AppEngine::Property::StandardAppVersionDeployment.new(@fetched['deployment'], to_s)
    @entrypoint = GoogleInSpec::AppEngine::Property::StandardAppVersionEntrypoint.new(@fetched['entrypoint'], to_s)
    @service = @fetched['service']
  end

  # Handles parsing RFC3339 time string
  def parse_time_string(time_string)
    time_string ? Time.parse(time_string) : nil
  end

  def exists?
    !@fetched.nil?
  end

  def to_s
    "StandardAppVersion #{@params[:version_id]}"
  end

  private

  def product_url
    'https://appengine.googleapis.com/v1/'
  end

  def resource_base_url
    'apps/{{project}}/services/{{service}}/versions/{{version_id}}'
  end
end
