# Copyright 2018 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------

require 'google/compute/property/firewall_allowed'
require 'google/compute/property/firewall_denied'
require 'google/hash_utils'
require 'inspec/resource'

# A provider to manage Google Compute Engine resources.
class Firewall < Inspec.resource(1)

  name 'google_compute_firewall'
  desc 'Firewall'
  supports platform: 'gcp2'

  attr_reader :allowed
  attr_reader :creation_timestamp
  attr_reader :denied
  attr_reader :description
  attr_reader :destination_ranges
  attr_reader :direction
  attr_reader :disabled
  attr_reader :id
  attr_reader :name
  attr_reader :network
  attr_reader :priority
  attr_reader :source_ranges
  attr_reader :source_service_accounts
  attr_reader :source_tags
  attr_reader :target_service_accounts
  attr_reader :target_tags
  def base
    'https://www.googleapis.com/compute/v1/'
  end

  def url
    'projects/{{project}}/global/firewalls/{{name}}'
  end

  def initialize(params)
    @fetched = fetch_resource(params)
    parse unless @fetched.nil?
  end

  def fetch_resource(params)
    get_request = inspec.backend.fetch(base, url, params)
  end

  def initialize(params)
    @fetched = fetch_resource(params)
    parse unless @fetched.nil?
  end

  def fetch_resource(params)
    get_request = inspec.backend.fetch(base, url, params)
  end

  def parse
    @allowed = Google::Compute::Property::FirewallAllowedArray.parse(@fetched['allowed'])
    @creation_timestamp = DateTime.parse(@fetched['creationTimestamp'])
    @denied = Google::Compute::Property::FirewallDeniedArray.parse(@fetched['denied'])
    @description = @fetched['description']
    @destination_ranges = @fetched['destinationRanges']
    @direction = @fetched['direction']
    @disabled = @fetched['disabled']
    @id = @fetched['id']
    @name = @fetched['name']
    @network = @fetched['network']
    @priority = @fetched['priority']
    @source_ranges = @fetched['sourceRanges']
    @source_service_accounts = @fetched['sourceServiceAccounts']
    @source_tags = @fetched['sourceTags']
    @target_service_accounts = @fetched['targetServiceAccounts']
    @target_tags = @fetched['targetTags']
  end

  def exists?
    !@fetched.nil?
  end

end
